name: context checking
on: push
jobs: 
  context-demo:
    runs-on: ubuntu-latest
    steps:
      - name: git details
        run: echo "This is from this git id ${{ github.actor}}
             echo "this is form this reposiotry ${{github.repository}}
   
