name: If Else workflows
on:
 workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checking the branch
        if: github.ref_name == 'main'
        run: echo "running for the main branch"
  Deloy:
    runs-on: ubuntu-latest
    steps:
      - name: deploying the branch
        if: github.ref_name == 'main'
        run: echo "deplying the main branch"
