name: Build Test Deploy

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Step
        run: echo "Hello World from ${{vars.Name}}, ${{secrets.Pass_key}}"
