name: Html file added

on: 
  push:
    branches:
      - main

jobs:
  action-demo:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code  
        uses: actions/checkout@v4
      - name: Print the Index 
        run: cat index.html
