name: Build Test Deploy

on: 
 push:
    branches:
      - Develop
  
 pull_request:
    types: [opened,synchronize]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Step
        run: echo "Hello World from hiii"

