name: Diffrent ouput accessing
on:
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the Ouput
        id: step1
        run: echo "Setting the Version"
              echo "Version=0.01" >> $GITHUB_OUTPUT
      - name: Print the Output continue-on-error
        run: echo " the version the output is ${{steps.step1.outputs.Version}}
              
